/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AirlineTicketBookingSystemGUI;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

/**
 *
 * @author Xiaofeng Wang
 */
public class SeatChoice extends JFrame {

    //varaible being declared
    
    private JLabel Prompt1;
    private JLabel Prompt2;
    private JTextField SeatChoice;
    public JButton [][] seating;
    private final DrawPanel drawPanel;
    
    /**
     * Creates new form SeatChoice
     */
    public SeatChoice() {
        initComponents();
        drawPanel = new DrawPanel();
        drawPanel.repaint();
        
        seating = new JButton[5][10];
        for (JButton[] seating1 : seating) {
            for (int y = 0; y < seating1.length; y++) {
                seating1[y] = new JButton();
            }
        }
        super.add(drawPanel);
    }
    
    public class DrawPanel extends JPanel{
        public DrawPanel(){
            super.setPreferredSize(new Dimension(400,400));
        }

        protected void paintComponenet (Graphics g){
            super.paintComponent(g);
            for(int x = 0; x < seating.length; x++){
                for(int y = 0; y < seating[x].length; y++){
                    seating[x][y].setBounds(x*1, y*30, 30, 30);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        SeatChoice = new JTextField();
        Prompt2 = new JLabel();
        Prompt1 = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        SeatChoice.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                SeatChoiceActionPerformed(evt);
            }
        });

        Prompt2.setText("Seat Choice");

        Prompt1.setText("Please Click A Button To Select A Seat");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Prompt1, GroupLayout.PREFERRED_SIZE, 215, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(Prompt2)
                    .addComponent(SeatChoice, GroupLayout.PREFERRED_SIZE, 62, GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(Prompt1, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                    .addComponent(Prompt2))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeatChoice, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void SeatChoiceActionPerformed(ActionEvent evt) {                                           
        if(evt.getSource() == seating){
            
        }
    }                                          

    /**
     * @param args the command line arguments
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeatChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeatChoice().setVisible(true);
            }
        });
    }

             
}

